name: Unix Build

on:
  schedule:
    - cron: '0 3 * * 2,6'
  push:
    branches: [ master, rsl-viz ]
  pull_request:
    branches: [ master, rsl-viz ]
  release:
    types:
      - published

jobs:
  rsl-ui-checks:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ui/rsl
    steps:
      - uses: actions/checkout@v2

      - name: pnpm Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install RSL Web Interface Dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.1
          run_install: |
            - cwd: ui/rsl

      - name: Formatting
        run: pnpm run format-check

      - name: ESLint
        run: pnpm run lint

      - name: TypeScript
        run: pnpm run ts-check

      - name: Build
        run: pnpm run build
